To-Do-List Application: Database Class Reference
Database Class Reference
Classe représentant une base de données simple pour stocker et gérer des tâches.
#include <database.h>
Signals
void tacheModelChanged ()
Signal émis lorsqu'une modification des tâches se produit.
Public Member Functions
Database (const Database &)=delete
Constructeur de copie supprimé.
Database & operator= (const Database &)=delete
Opérateur d'affectation supprimé.
Q_INVOKABLE bool createTable ()
Initialise la connexion à la base de données SQLite et crée la table si elle n'existe pas.
Q_INVOKABLE void addTache (QSharedPointer< Tache > tache)
Ajoute une tâche à la base de données.
Q_INVOKABLE bool removeTache (int id)
Supprime une tâche de la base de données.
QSharedPointer< Tache > getTache (int id)
Récupère une tâche par son identifiant.
QList< QSharedPointer< Tache > > getAllTaches ()
Récupère toutes les tâches de la base de données.
Q_INVOKABLE bool updateTache (Tache *tache)
Met à jour une tâche existante dans la base de données.
Database (QObject *parent=nullptr)
Constructeur de la classe Database.
~Database ()
Destructeur de la classe Database.
void updateModel ()
Met à jour le modèle des tâches en chargeant les données depuis la base de données.
Static Public Member Functions
static Database & instance ()
Accède à l'instance unique du singleton Database.
Public Attributes
QSqlDatabase m_db
QList< QSharedPointer< Tache > > m_taches
Detailed Description
Classe représentant une base de données simple pour stocker et gérer des tâches.
Cette classe encapsule une collection de tâches et fournit des méthodes pour ajouter, supprimer, modifier et récupérer les tâches.
Definition at line 20 of file database.h.
Constructor & Destructor Documentation
Database() [1/2]
Database::Database (const Database &) delete
Constructeur de copie supprimé.
Cette méthode supprime le constructeur de copie pour éviter la duplication de l'instance unique du singleton Database.
Parameters
other L'objet Database à copier.
Database() [2/2]
Database::Database (QObject * parent = nullptr) explicit
Constructeur de la classe Database.
Initialise de la base de données SQLite
Definition at line 9 of file database.cpp.
    : QObject(parent) {
    // Initialisation de la base de données SQLite
    m_db = QSqlDatabase::addDatabase("QSQLITE");
    m_db.setDatabaseName("taches.db");
    if (!m_db.open()) {
        qDebug() << "Erreur lors de l'ouverture de la base de données:" << m_db.lastError();
    } else {
        qDebug() << "Base de données ouverte avec succès.";
        updateModel();  // Initialiser le modèle lorsque la base de données est ouverte
    //     QSqlQuery query;
    //     // Création de la table si elle n'existe pas
    //     QString createTableQuery = "CREATE TABLE IF NOT EXISTS taches ("
    //                                "id INTEGER PRIMARY KEY, "
    //                                "titre TEXT, "
    //                                "note TEXT, "
    //                                "dateHeure TEXT, "
    //                                "isCompleted INTEGER, "
    //                                "priority INTEGER)";
    //     if (!query.exec(createTableQuery)) {
    //         qDebug() << "Erreur lors de la création de la table:" << query.lastError();
    //     }
    //     else {
    //         qDebug() << "Table 'taches' créée ou déjà existante.";
    //         // Charger toutes les tâches de la base de données dans le vecteur m_taches
    //         query.exec("SELECT * FROM taches");
    //         while (query.next()) {
    //             Tache* tache = new Tache(
    //                 query.value("id").toInt(),
    //                 query.value("titre").toString(),
    //                 query.value("note").toString(),
    //                 query.value("dateHeure").toString(),
    //                 static_cast<Priority>(query.value("priority").toInt())
    //                 );
    //             tache->setCompleted(query.value("isCompleted").toBool());
    //             m_taches.append(tache);
    //         }
    //     }
    }
}
References m_db, and updateModel().
~Database()
Database::~Database ()
Destructeur de la classe Database.
Libérer la mémoire des tâches er ferme la connexion à la base de données.
Definition at line 51 of file database.cpp.
                    {
    //qDeleteAll(m_taches);
    m_taches.clear();
    m_db.close();
}
References m_db, and m_taches.
Member Function Documentation
addTache()
void Database::addTache (QSharedPointer< Tache > tache)
Ajoute une tâche à la base de données.
Parameters
tache Pointeur vers la tâche à ajouter.
Definition at line 74 of file database.cpp.
{
    QSqlQuery query;
    query.prepare("INSERT INTO taches (titre, note, dateHeure, isCompleted, priority) "
                  "VALUES (:titre, :note, :dateHeure, :isCompleted, :priority)");
    query.bindValue(":titre", tache->getTitre());
    query.bindValue(":note", tache->getNote());
    query.bindValue(":dateHeure", tache->getDateHeure());
    query.bindValue(":isCompleted", tache->getCompleted());
    query.bindValue(":priority", static_cast<int>(tache->getPriority()));
    if (query.exec()) {
        tache->setId(query.lastInsertId().toInt());
        m_taches.append(tache);  // Ajouter la tâche au vecteur
        emit tacheModelChanged();  // Émet le signal après l'ajout
        qDebug() << "tache ajoutée à la liste des taches";
    } else {
        qDebug() << "Erreur lors de l'ajout de la tâche:" << query.lastError();
    }
}
References m_taches, and tacheModelChanged().
createTable()
bool Database::createTable ()
Initialise la connexion à la base de données SQLite et crée la table si elle n'existe pas.
Returns
True si la tâche a été supprimée avec succès, False sinon.
Definition at line 57 of file database.cpp.
{
        QSqlQuery query;
        if (!query.exec("CREATE TABLE IF NOT EXISTS taches ("
                        "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                        "titre TEXT,"
                        "note TEXT,"
                        "dateHeure TEXT,"
                        "isCompleted INTEGER,"
                        "priority INTEGER)")) {
            qDebug() << "Erreur lors de la création de la table:" << query.lastError();
            return false;  // Ajoutez un retour en cas d'erreur
        } else {
            qDebug() << "Table 'taches' créée ou déjà existante.";
            return true;
        }
}
getAllTaches()
QList< QSharedPointer< Tache > > Database::getAllTaches ()
Récupère toutes les tâches de la base de données.
Returns
Vecteur contenant des pointeurs vers toutes les tâches.
Definition at line 125 of file database.cpp.
{
    updateModel();
    return m_taches;
}
References m_taches, and updateModel().
getTache()
QSharedPointer< Tache > Database::getTache (int id)
Récupère une tâche par son identifiant.
Parameters
id Identifiant de la tâche à récupérer.
Returns
Pointeur vers la tâche correspondante ou nullptr si elle n'existe pas.
Definition at line 116 of file database.cpp.
{
    for (const auto& tache : m_taches) {
        if (tache->getId() == id) {
            return tache;
        }
    }
    return nullptr;
}
References m_taches.
instance()
Database & Database::instance () static
Accède à l'instance unique du singleton Database.
Cette méthode retourne une référence à l'unique instance de la classe Database. Si l'instance n'existe pas encore, elle est créée.
Returns
Référence à l'instance unique de Database.
Definition at line 4 of file database.cpp.
{
    static Database instance;
    return instance;
}
References instance().
operator=()
Database & Database::operator= (const Database &) delete
Opérateur d'affectation supprimé.
Cette méthode supprime l'opérateur d'affectation pour éviter d'affecter une nouvelle valeur à l'instance unique du singleton Database.
Parameters
other L'objet Database à affecter.
Returns
Référence à l'instance actuelle de Database.
removeTache()
bool Database::removeTache (int id)
Supprime une tâche de la base de données.
Parameters
id Identifiant de la tâche à supprimer.
Returns
True si la tâche a été supprimée avec succès, False sinon.
Definition at line 94 of file database.cpp.
{
    QSqlQuery query;
    query.prepare("DELETE FROM taches WHERE id = :id");
    query.bindValue(":id", id);
    if (query.exec()) {
        for (int i = 0; i < m_taches.size(); ++i) {
            if (m_taches[i]->getId() == id) {
                //delete m_taches[i];
                m_taches.remove(i);  // Supprimer la tâche du vecteur
                emit tacheModelChanged();  // Émet le signal après la suppression
                qDebug() << "tache supprimée de la liste des taches";
                break;
            }
        }
        return true;
    } else {
        qDebug() << "Erreur lors de la suppression de la tâche:" << query.lastError();
        return false;
    }
}
References m_taches, and tacheModelChanged().
tacheModelChanged
void Database::tacheModelChanged () signal
Signal émis lorsqu'une modification des tâches se produit.
Ce signal peut être connecté à l'interface utilisateur pour garantir que celle-ci est mise à jour.
Definition at line 193 of file moc_database.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 0, nullptr);
}
updateModel()
void Database::updateModel ()
Met à jour le modèle des tâches en chargeant les données depuis la base de données.
Libérer la mémoire des tâches er ferme la connexion à la base de données.
Definition at line 153 of file database.cpp.
{
    m_taches.clear();
    QSqlQuery query;
    // Charger toutes les tâches de la base de données dans le vecteur m_taches
    if (!query.exec("SELECT * FROM taches")) {
        qDebug() << "Erreur lors du chargement des tâches:" << query.lastError();
    }
    while (query.next()) {
        QSharedPointer<Tache> tache = QSharedPointer<Tache>::create(
            query.value("id").toInt(),
            query.value("titre").toString(),
            query.value("note").toString(),
            query.value("dateHeure").toString(),
            static_cast<Priority>(query.value("priority").toInt())
            );
        tache->setCompleted(query.value("isCompleted").toBool());
        m_taches.append(tache);
    }
    emit tacheModelChanged();  // Notifier QML que le modèle a changé
}
References m_taches, and tacheModelChanged().
updateTache()
bool Database::updateTache (Tache * tache)
Met à jour une tâche existante dans la base de données.
Parameters
tache Pointeur vers la tâche mise à jour.
Returns
True si la mise à jour a été effectuée avec succès, False sinon.
Definition at line 131 of file database.cpp.
{
    QSqlQuery query;
    query.prepare("UPDATE taches SET titre = :titre, note = :note, dateHeure = :dateHeure, "
                  "isCompleted = :isCompleted, priority = :priority WHERE id = :id");
    query.bindValue(":titre", tache->getTitre());
    query.bindValue(":note", tache->getNote());
    query.bindValue(":dateHeure", tache->getDateHeure());
    query.bindValue(":isCompleted", tache->getCompleted());
    query.bindValue(":priority", static_cast<int>(tache->getPriority()));
    query.bindValue(":id", tache->getId());
    if (query.exec()) {
        qDebug() << "TACHE MODIFIE";
        updateModel();
        return true;
    } else {
        qDebug() << "Erreur lors de la mise à jour de la tâche:" << query.lastError();
    }
}
References Tache::getCompleted(), Tache::getDateHeure(), Tache::getId(), Tache::getNote(), Tache::getPriority(), Tache::getTitre(), and updateModel().
Member Data Documentation
m_db
QSqlDatabase Database::m_db
Definition at line 118 of file database.h.
m_taches
QList<QSharedPointer<Tache> > Database::m_taches
Definition at line 119 of file database.h.
The documentation for this class was generated from the following files:
database.h
build/Qt_6_7_2-Debug/appTo-Do-List_autogen/EWIEGA46WW/moc_database.cpp
database.cpp