To-Do-List Application: Tache Class Reference
Tache Class Reference
Classe représentant une tâche avec un titre, une note, une date, un état d'accomplissement et une priorité.
#include <tache.h>
Signals
void idChanged ()
Emission d'un signal lors du changement d'id.
void titreChanged ()
Emission d'un signal lors du changement de titre.
void noteChanged ()
Emission d'un signal lors du changement de note.
void dateHeureChanged ()
Emission d'un signal lors du changement de date et heure.
void isCompletedChanged ()
Emission d'un signal lors du changement du statut de validation.
void priorityChanged ()
Emission d'un signal lors du changement de priorité
Public Member Functions
Tache ()
Constructeur par défaut de la classe Tache.
Tache (int id, const QString &titre, const QString &note, const QString &dateHeure, Priority priority)
Constructeur avec paramètres pour créer une tâche.
~Tache ()
Destructeur de la classe Tache.
void setId (const int &id)
Modifie l'identifiant de la tâche.
int getId ()
Récupère l'identifiant de la tâche.
void setTitre (const QString &titre)
Modifie le titre de la tâche.
QString getTitre ()
Récupère le titre de la tâche.
void setNote (const QString &note)
Modifie la note de la tâche.
QString getNote ()
Récupère la note de la tâche.
void setDateHeure (const QString &dateTime)
Modifie la date et l'heure de la tâche.
QString getDateHeure ()
Récupère la date et l'heure de la tâche.
Q_INVOKABLE QString getDateHeureNow ()
Récupère la date et l'heure actuelle.
void setCompleted (bool val)
Modifie l'état d'accomplissement de la tâche.
bool getCompleted ()
Récupère l'état d'accomplissement de la tâche.
void setPriority (Priority priority)
Modifie la priorité de la tâche.
Priority getPriority ()
Récupère la priorité de la tâche.
Properties
QML_ELEMENTint id
QString titre
QString note
QString dateHeure
bool isCompleted
Priority priority
Private Attributes
int m_id
QString m_titre
QString m_note
QString m_dateHeure
bool m_isCompleted
Priority m_priority
Detailed Description
Classe représentant une tâche avec un titre, une note, une date, un état d'accomplissement et une priorité.
Cette classe encapsule les informations d'une tâche et fournit des méthodes pour accéder et modifier ces informations.
Definition at line 25 of file tache.h.
Constructor & Destructor Documentation
Tache() [1/2]
Tache::Tache ()
Constructeur par défaut de la classe Tache.
Initialise une tâche avec des valeurs par défaut.
Definition at line 4 of file tache.cpp.
            : m_id(0), m_titre(""), m_note(""), m_dateHeure(/*QDateTime::currentDateTime()*/""), m_isCompleted(false), m_priority(Priority::MEDIUM)
{}
Tache() [2/2]
Tache::Tache (int id, const QString & titre, const QString & note, const QString & dateHeure, Priority priority)
Constructeur avec paramètres pour créer une tâche.
Parameters
id Identifiant unique de la tâche.
titre Titre de la tâche.
note Note associée à la tâche.
dateHeure Date et heure associées à la tâche.
priority Niveau de priorité de la tâche.
Definition at line 7 of file tache.cpp.
    : m_id(id), m_titre(titre), m_note(note), m_dateHeure(dateHeure), m_isCompleted(false), m_priority(priority)
{}
~Tache()
Tache::~Tache ()
Destructeur de la classe Tache.
Definition at line 105 of file tache.cpp.
{
}
Member Function Documentation
dateHeureChanged
void Tache::dateHeureChanged () signal
Emission d'un signal lors du changement de date et heure.
Definition at line 295 of file moc_Tache.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 3, nullptr);
}
getCompleted()
bool Tache::getCompleted ()
Récupère l'état d'accomplissement de la tâche.
Returns
Booléen indiquant si la tâche est accomplie.
Definition at line 85 of file tache.cpp.
{
    return m_isCompleted;
}
References m_isCompleted.
getDateHeure()
QString Tache::getDateHeure ()
Récupère la date et l'heure de la tâche.
Returns
Date et heure de la tâche sous forme de QDateTime.
Definition at line 63 of file tache.cpp.
{
    return m_dateHeure;
}
References m_dateHeure.
getDateHeureNow()
QString Tache::getDateHeureNow ()
Récupère la date et l'heure actuelle.
Returns
Date et heure de la tâche sous forme de QDateTime.
Definition at line 68 of file tache.cpp.
{
    QDateTime dateHeure = QDateTime::currentDateTime();
    QString formattedString = dateHeure.toString("dd/MM/yyyy HH:mm AP");
    return formattedString;
}
References dateHeure.
getId()
int Tache::getId ()
Récupère l'identifiant de la tâche.
Returns
Identifiant unique de la tâche.
Definition at line 21 of file tache.cpp.
{
    return m_id;
}
References m_id.
getNote()
QString Tache::getNote ()
Récupère la note de la tâche.
Returns
Note associée à la tâche.
Definition at line 48 of file tache.cpp.
{
    return m_note;
}
References m_note.
getPriority()
Priority Tache::getPriority ()
Récupère la priorité de la tâche.
Returns
Priorité de la tâche.
Definition at line 99 of file tache.cpp.
{
    return m_priority;
}
References m_priority.
getTitre()
QString Tache::getTitre ()
Récupère le titre de la tâche.
Returns
Titre de la tâche sous forme de QString.
Definition at line 34 of file tache.cpp.
{
    return m_titre;
}
References m_titre.
idChanged
void Tache::idChanged () signal
Emission d'un signal lors du changement d'id.
Definition at line 277 of file moc_Tache.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 0, nullptr);
}
isCompletedChanged
void Tache::isCompletedChanged () signal
Emission d'un signal lors du changement du statut de validation.
Definition at line 301 of file moc_Tache.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 4, nullptr);
}
noteChanged
void Tache::noteChanged () signal
Emission d'un signal lors du changement de note.
Definition at line 289 of file moc_Tache.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 2, nullptr);
}
priorityChanged
void Tache::priorityChanged () signal
Emission d'un signal lors du changement de priorité
Definition at line 307 of file moc_Tache.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 5, nullptr);
}
setCompleted()
void Tache::setCompleted (bool val)
Modifie l'état d'accomplissement de la tâche.
Parameters
val Booléen indiquant si la tâche est accomplie.
Definition at line 77 of file tache.cpp.
{
    if (m_isCompleted != val) {
        m_isCompleted = val;
        emit isCompletedChanged();
    }
}
References isCompletedChanged(), and m_isCompleted.
setDateHeure()
void Tache::setDateHeure (const QString & dateTime)
Modifie la date et l'heure de la tâche.
Parameters
dateTime Référence à la nouvelle date et heure.
Definition at line 54 of file tache.cpp.
{
    if (m_dateHeure != dateTime) {
        m_dateHeure = dateTime;
        emit dateHeureChanged();
    }
}
References dateHeureChanged(), and m_dateHeure.
setId()
void Tache::setId (const int & id)
Modifie l'identifiant de la tâche.
Parameters
id Référence à l'identifiant de la tâche.
Definition at line 13 of file tache.cpp.
{
    if(m_id != id){
        m_id = id;
        emit idChanged();
    }
}
References id, idChanged(), and m_id.
setNote()
void Tache::setNote (const QString & note)
Modifie la note de la tâche.
Parameters
note Référence à la note de la tâche.
Definition at line 40 of file tache.cpp.
{
    if(m_note != note){
        m_note = note;
        emit noteChanged();
    }
}
References m_note, note, and noteChanged().
setPriority()
void Tache::setPriority (Priority priority)
Modifie la priorité de la tâche.
Parameters
priority Nouvelle priorité de la tâche.
Definition at line 91 of file tache.cpp.
{
    if (m_priority != priority) {
        m_priority = priority;
        emit priorityChanged();
    }
}
References m_priority, priority, and priorityChanged().
setTitre()
void Tache::setTitre (const QString & titre)
Modifie le titre de la tâche.
Parameters
titre Référence au titre de la tâche.
Definition at line 26 of file tache.cpp.
{
    if(m_titre != titre){
        m_titre = titre;
        emit titreChanged();
    }
}
References m_titre, titre, and titreChanged().
titreChanged
void Tache::titreChanged () signal
Emission d'un signal lors du changement de titre.
Definition at line 283 of file moc_Tache.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 1, nullptr);
}
Member Data Documentation
m_dateHeure
QString Tache::m_dateHeure private
Definition at line 159 of file tache.h.
m_id
int Tache::m_id private
Definition at line 156 of file tache.h.
m_isCompleted
bool Tache::m_isCompleted private
Definition at line 160 of file tache.h.
m_note
QString Tache::m_note private
Definition at line 158 of file tache.h.
m_priority
Priority Tache::m_priority private
Definition at line 161 of file tache.h.
m_titre
QString Tache::m_titre private
Definition at line 157 of file tache.h.
Property Documentation
dateHeure
QString Tache::dateHeure read write
Definition at line 33 of file tache.h.
id
QML_ELEMENTint Tache::id read write
Definition at line 30 of file tache.h.
isCompleted
bool Tache::isCompleted read write
Definition at line 34 of file tache.h.
note
QString Tache::note read write
Definition at line 32 of file tache.h.
priority
Priority Tache::priority read write
Definition at line 35 of file tache.h.
titre
QString Tache::titre read write
Definition at line 31 of file tache.h.
The documentation for this class was generated from the following files:
tache.h
build/Qt_6_7_2-Debug/appTo-Do-List_autogen/EWIEGA46WW/moc_Tache.cpp
tache.cpp