To-Do-List Application: GestionTaches Class Reference
GestionTaches Class Reference
Classe permettant de gérer une liste de tache.
#include <GestionTaches.h>
Signals
void tacheUpdate ()
Signal émis lorsque une tache est ajoutée, supprimée, ou modifiée.
void tacheAdded ()
Public Member Functions
GestionTaches ()
Constructeur par défaut de la classe GestionTaches.
~GestionTaches ()
Destructeur de la classe GestionTaches.
void ajouterTache (QSharedPointer< Tache > &tache)
Ajoute une tâche déjà créée à la liste des tâches.
Q_INVOKABLE void ajouterTache (int id, const QString &titre, const QString &note, const QString &dateHeure, Priority priority)
Crée et ajoute une tâche à la liste avec les attributs spécifiés.
Q_INVOKABLE void ajouterTacheRapide (int id, const QString &titre)
Crée et ajoute une tâche à la date actuelle en ne renseignant que le titre, depuis l'écran principal.
Q_INVOKABLE void supprimerTache (int id)
Supprime une tâche de la liste en fonction de son identifiant.
Q_INVOKABLE void modifierTache (int id, Tache *nouvelleTache)
Modifie une tâche existante avec une nouvelle tâche.
Q_INVOKABLE QSharedPointer< Tache > getTache (int id) const
Récupère une tâche à partir de son identifiant.
QList< QSharedPointer< Tache > > getListeTaches () const
Récupère la liste complète des tâches.
QVariantList getTachesAsVariantList () const
Properties
QVariantList listeTaches
Private Attributes
QList< QSharedPointer< Tache > > listeTaches
Liste des tâches.
Detailed Description
Classe permettant de gérer une liste de tache.
Cette classe implémente des méthodes pour créer, modifier, supprimer et récupérer des tâches. Elle comporte un conteneur de liste de tâches gérant l'intégralité des tâches du programme.
Definition at line 16 of file GestionTaches.h.
Constructor & Destructor Documentation
GestionTaches()
GestionTaches::GestionTaches ()
Constructeur par défaut de la classe GestionTaches.
Definition at line 3 of file GestionTaches.cpp.
{
    /*
     QString format = "dd/MM/yyyy hh:mm AP";
    //Valeurs de tests en dur
    //Section today
    ajouterTache(0, "Tache 1", "note 1", QDateTime::currentDateTime().toString(format), Priority::HIGH);
    ajouterTache(1, "Tache 2", "note 2", QDateTime::currentDateTime().toString(format), Priority::LOW);
    ajouterTache(2, "Tache 3", "note 3", QDateTime::currentDateTime().toString(format), Priority::HIGH);
    ajouterTache(3, "Tache 4", "note 4", QDateTime::currentDateTime().toString(format), Priority::MEDIUM);
    //Section this week
    ajouterTache(4, "Tache 5", "note 5", "06/09/2024 11:21 AM", Priority::MEDIUM);
    ajouterTache(5, "Tache 6", "note 6", "07/09/2024 11:21 AM", Priority::MEDIUM);
    ajouterTache(6, "Tache 7", "note 7", "06/09/2024 03:30 AM", Priority::MEDIUM);
    //Section Later
    ajouterTache(7, "Tache 8", "note 8", "05/11/2025 11:21 AM", Priority::MEDIUM);
    ajouterTache(8, "Tache 9", "note 9", "05/01/2027 11:21 AM", Priority::MEDIUM);
    ajouterTache(10, "Tache 11", "note 11", "25/12/2024 11:21 AM", Priority::MEDIUM);
    ajouterTache(11, "Tache 12", "note 12", "25/11/2026 11:21 AM", Priority::MEDIUM);
    //Non valide (antérieure)
    ajouterTache(9, "Tache 10", "note 10", "05/01/2024 11:21 AM", Priority::MEDIUM);
*/
}
~GestionTaches()
GestionTaches::~GestionTaches ()
Destructeur de la classe GestionTaches.
Definition at line 31 of file GestionTaches.cpp.
{
}
Member Function Documentation
ajouterTache() [1/2]
void GestionTaches::ajouterTache (int id, const QString & titre, const QString & note, const QString & dateHeure, Priority priority)
Crée et ajoute une tâche à la liste avec les attributs spécifiés.
Parameters
id Identifiant unique de la tâche.
titre Titre de la tâche.
note Note associée à la tâche.
dateHeure Date et heure de la tâche.
priority Priorité de la tâche.
Definition at line 42 of file GestionTaches.cpp.
{
    QSharedPointer<Tache> newTache = QSharedPointer<Tache>::create(id, titre, note, dateHeure, priority);
    listeTaches.append(newTache);
    emit tacheAdded();
}
References listeTaches, and tacheAdded().
ajouterTache() [2/2]
void GestionTaches::ajouterTache (QSharedPointer< Tache > & tache)
Ajoute une tâche déjà créée à la liste des tâches.
Parameters
tache Référence à une tâche déja créée, à ajouter à la liste.
Definition at line 36 of file GestionTaches.cpp.
{
    listeTaches.append(tache);
    emit tacheAdded();
}
References listeTaches, and tacheAdded().
ajouterTacheRapide()
void GestionTaches::ajouterTacheRapide (int id, const QString & titre)
Crée et ajoute une tâche à la date actuelle en ne renseignant que le titre, depuis l'écran principal.
Parameters
titre Titre de la tâche.
Definition at line 51 of file GestionTaches.cpp.
{
    QDateTime dateHeure = QDateTime::currentDateTime();
    QString formattedString = dateHeure.toString("yyyy-MM-dd HH:mm:ss");
    ajouterTache(id, titre, "", formattedString, Priority::MEDIUM);
    emit tacheAdded();
}
References ajouterTache(), MEDIUM, and tacheAdded().
getListeTaches()
QList< QSharedPointer< Tache > > GestionTaches::getListeTaches () const
Récupère la liste complète des tâches.
Returns
QList Liste contenant toutes les pointeur sur les tâches.
Definition at line 105 of file GestionTaches.cpp.
{
    return listeTaches;
}
References listeTaches.
getTache()
QSharedPointer< Tache > GestionTaches::getTache (int id) const
Récupère une tâche à partir de son identifiant.
Parameters
id Identifiant unique de la tâche à récupérer.
Returns
Tache Tache correspondant à l'identifiant renseigné.
Definition at line 95 of file GestionTaches.cpp.
{
    for (const auto& tache : listeTaches) {
        if (tache->getId() == id) {
            return tache;
        }
    }
    return QSharedPointer<Tache>(nullptr);
}
References listeTaches.
getTachesAsVariantList()
QVariantList GestionTaches::getTachesAsVariantList () const
Definition at line 111 of file GestionTaches.cpp.
{
    Database& database = Database::instance();
    const auto& allTaches = database.getAllTaches();
    QVariantList variantList;
    for (const auto& tache : allTaches) {
        QVariantMap tacheMap;
        tacheMap["id"] = tache->getId();
        tacheMap["titre"] = tache->getTitre();
        tacheMap["note"] = tache->getNote();
        tacheMap["dateHeure"] = tache->getDateHeure();
        tacheMap["priority"] = static_cast<int>(tache->getPriority());
        tacheMap["isCompleted"] = tache->getCompleted();
        variantList.append(tacheMap);
    }
    return variantList;
}
References Database::getAllTaches(), and Database::instance().
modifierTache()
void GestionTaches::modifierTache (int id, Tache * nouvelleTache)
Modifie une tâche existante avec une nouvelle tâche.
Parameters
id Identifiant unique de la tâche à modifier.
nouvelleTache Référence à la nouvelle tâche qui remplacera l'ancienne.
Definition at line 72 of file GestionTaches.cpp.
{
    QSharedPointer<Tache> newTache = QSharedPointer<Tache>::create();
    newTache->setId(nouvelleTache->getId());
    newTache->setTitre(nouvelleTache->getTitre());
    newTache->setDateHeure(nouvelleTache->getDateHeure());
    newTache->setNote(nouvelleTache->getNote());
    newTache->setPriority(nouvelleTache->getPriority());
    qDebug() << "recherche de l'id : " << nouvelleTache->getId();
    for (int i = 0; i < listeTaches.size(); ++i) {
        qDebug() << "i =  " << i << " id = " << listeTaches[i]->getId();
        if (listeTaches[i]->getId() == id) {
            qDebug() << "TACHE MODIFIEEEEEEEEEEEE";
            listeTaches[i] = newTache;
            emit tacheUpdate();
            return;
        }
    }
    emit tacheUpdate();
}
References Tache::getDateHeure(), Tache::getId(), Tache::getNote(), Tache::getPriority(), Tache::getTitre(), listeTaches, and tacheUpdate().
supprimerTache()
void GestionTaches::supprimerTache (int id)
Supprime une tâche de la liste en fonction de son identifiant.
Parameters
id Identifiant unique de la tâche à supprimer.
Definition at line 60 of file GestionTaches.cpp.
{
    for (int i = 0; i < listeTaches.size(); ++i) {
        if (listeTaches[i]->getId() == id) {
            listeTaches.removeAt(i);
            emit tacheUpdate();
            return;
        }
    }
    emit tacheUpdate();
}
References listeTaches, and tacheUpdate().
tacheAdded
void GestionTaches::tacheAdded () signal
Definition at line 243 of file moc_GestionTaches.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 1, nullptr);
}
tacheUpdate
void GestionTaches::tacheUpdate () signal
Signal émis lorsque une tache est ajoutée, supprimée, ou modifiée.
Definition at line 237 of file moc_GestionTaches.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 0, nullptr);
}
Member Data Documentation
listeTaches
QList<QSharedPointer<Tache> > GestionTaches::listeTaches private
Liste des tâches.
Definition at line 96 of file GestionTaches.h.
Property Documentation
listeTaches
QVariantList GestionTaches::listeTaches read
Definition at line 20 of file GestionTaches.h.
The documentation for this class was generated from the following files:
GestionTaches.h
build/Qt_6_7_2-Debug/appTo-Do-List_autogen/EWIEGA46WW/moc_GestionTaches.cpp
GestionTaches.cpp